NYTimes Clone Nearly Finished - Need some help
ndjerrou/NYTimes_Clone pull request #1
Opened 2019-06-12 09:19 UTC by ndjerrou

Hello there,

I hope that you will be fine.

Can you help us finishing our project ?

We got some serious problems positionnant efficiently the asides bar on the right ? the two on our code with an id of "floating-sidebar" (there is two).

Thanks !

2019-06-12 14:25 UTC, Torres-ssf requested changes
### Congratulations Team 👏👏👏
This project is very big and you folks are showing a really good work on it 💪. Let's make the final necessary changes.

1. The project needs to have a descriptive README file.
2. Validate your HTML code in a validator webpage, it has some errors that you need to fix. Check this validator page: https://validator.w3.org/. You can also check errors in o CSS code in this CSS validator: https://jigsaw.w3.org/css-validator/
3. Most of your HTML errors are because you are using the same id for many elements. Ids must be unique for each element. You can use classes instead. In fact, using ids it's not a good practice, in 99% of the time, classes are a much better approach since you can reuse them in many elements as you want.  Check out this article https://dev.to/claireparkerjones/reasons-not-to-use-ids-in-css-4ni4. Use classes in your code instead of ids.
4. In the additional links section (More in Space and Cosmos and Editor's picks) you have some images without a figure tag. Please gently create figure tags for all those images and figcaption tags as well. Put only the captions inside the figcaption (don't put the links inside it). In the original page, each image has a caption describing it, create these captions and put inside the figcaption tags.
5. You don't need 2 aside tags. You can use only one. Delete the one which is causing you troubles: `aside id="first-floating-sidebar"` and put its content inside the other one: `aside id="second-floating-sidebar"`. You can divide these two using two divs inside the aside tag. Using position absolute it will be easier to match the original page. But you will need to re-style the new element(Editor's picks) to match the original page.
I've highlighted other changes that need to be made. Make them and submit for code review again. If you are struggling with something, please message me in the slack (Sérgio Torres) I will help you out.

2019-06-12 14:25 UTC, Torres-ssf commented on index.html
> +        <img src="./assets/images/The-New-York-Times-vector-logo.png" alt="" />
The NY logo must be a link. You can fix that putting the img tag inside an anchor tag.

2019-06-12 14:25 UTC, Torres-ssf commented on index.html
> +    <nav>
The navbar should be fixed in this project. Create a class for the nav tag, something like (class="navbar") and define these styles for it:

1. `position: fixed;` This will maintain the navbar on top of the page even when you scroll down.
2. `top: 0;` This works with the fixed position. With this you are telling the browser that the navbar must start at the very beginning of the page.
3. `width: 100%;` Make the navbar take the full width.
4. `background-color: white;` The default color after setting a fix position is transparent. To behave properly you have to set a background color.
5. `z-index: 10;` This change the z value of the element. So it will be on top of every element that has a z-index lower value.
6. `box-shadow: 0 2px 2px -2px rgba(0,0,0,.2);` And this create the little shadow effect on the bottom of the navbar. You can remove the hr tag

2019-06-12 14:25 UTC, Torres-ssf commented on index.html
> +            <iframe
You can also put videos inside the figure tag. It's a good practice.

2019-06-12 14:25 UTC, Torres-ssf commented on index.html
> +            </p>
Use the figcaption tag for video captions.

2019-06-12 14:25 UTC, Torres-ssf commented on index.html
> +          src="./assets/images/The-New-York-Times-vector-logo.png"
The NY time logo must be a link.

2019-06-12 14:25 UTC, Torres-ssf commented on index.html
> +          <h3>Most Popular</h3> -->
This section doesn't need to be an aside tag since it's part of the most related links. Divide the most related links into two parts. The left side for links with images and right for links only. The left part contains both 
*More in Space and Cosmos* and *Editor's picks* and the right part contains links only. You already did good in the left part, now just make this aside tag a div tag and put inside the related-articles section. Also, it's highly recommended use an unordered list(ul tag) in the right section(most popular links)

2019-06-13 10:15 UTC, ndjerrou commented on index.html
> +        <img src="./assets/images/The-New-York-Times-vector-logo.png" alt="" />
Okay, done.

thanks

2019-06-13 11:09 UTC, ndjerrou commented
@Torres-ssf Hey,

We've done with the changes u requested, thanks a lot for your help it really was helpful.

May u have a check please ?

Thanks a lot !

2019-06-13 18:02 UTC, maelfosso commented on index.html
> +        <div class="left-asidebar-part">
Please, gently use `figcaption` tag here

2019-06-13 18:03 UTC, maelfosso commented on index.html
> +      <aside id="second-floating-sidebar">
Here, You don't need 2 aside tags. You can use only one. Delete the one which is causing you troubles.

2019-06-13 18:04 UTC, maelfosso commented
HI,

Very good Job, but some things to change

- Please update the README: Put a description, the author's name with a link to their Github profile, a link of a live version. You could use (Githack or GH-Pages)

- Validate your HTML code in a validator webpage, it has still some errors that you need to fix. Check this validator page: https://validator.w3.org/. You can also check errors in o CSS code in this CSS validator: https://jigsaw.w3.org/css-validator/

- **Editor's Picks** section is not at a good position. Please check out your css code and complete it. And as it was said before, Please gently create figure tags for all those images and figcaption tags as well. Put only the captions inside the `figcaption` (don't put the links inside it). 

- You don't need 2 aside tags. You can use only one. Delete the one which is causing you troubles.

Please correct those issues and submit a new code review request.

2019-06-15 03:48 UTC, bellom requested changes
Hi @ndjerrou @themonster2015,
You guys have done a very good job, is just that you didn't preview your work before submitting another code review.
**Kindly do the following few things and let me give you thumbs-up...**
1. Correct the article positioning, screenshot from your web page below;

![image](https://user-images.githubusercontent.com/31897434/59546593-47592880-8f28-11e9-8f08-e47b6864545b.png)

**Correct the error and submit another code review and get thumbs-up.**
_Happy Coding_

2019-06-15 07:14 UTC, ndjerrou commented
> Hi @ndjerrou @themonster2015,
> You guys have done a very good job, is just that you didn't preview your work before submitting another code review.
> **Kindly do the following few things and let me give you thumbs-up...**
> 
> 1. Correct the article positioning, screenshot from your web page below;
> 
> ![image](https://user-images.githubusercontent.com/31897434/59546593-47592880-8f28-11e9-8f08-e47b6864545b.png)
> 
> **Correct the error and submit another code review and get thumbs-up.**
> _Happy Coding_

Hi,

We've made the correct changes but the link to the live project was not the good one .

here is the good one according to our last changes : 

[NYTimes CLONE](https://raw.githack.com/ndjerrou/NYTimes_Clone/dev/index.html)

2019-06-17 12:23 UTC, Torres-ssf commented
### Nice job team.
I'll give this project a 👍. Merge to master and don't forget to submit the form.

2019-06-17 15:48 UTC, merged